<a href="https://colab.research.google.com/github/icy-agarwal/AIML/blob/main/DAY3_pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#data cleaning process is called data munging or data wrangling

In [ ]:
#dataframe is used to represent data in tabular form

In [ ]:
df = pd.read_csv("first.csv")

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [ ]:
rows, columns = df.shape
rows

6

In [ ]:
columns

4

In [ ]:
df.head(2) #df.head() gives first five rows. a value in bracket means that many rows need to be printed

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [ ]:
df.tail() #last five rows

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [ ]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [ ]:
type(df['event'])

pandas.core.series.Series

In [ ]:
df[['event', 'day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [ ]:
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    32
Name: temperature, dtype: int64

In [ ]:
df['temperature'].max()

35

In [ ]:
df['temperature'].mean()

np.float64(30.5)

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [ ]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.500000   4.666667
std       3.885872   2.338090
min      24.000000   2.000000
25%      29.000000   2.500000
50%      32.000000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df[df.temperature>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [ ]:
df[df.temperature==df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df[['day', 'temperature']][df.temperature==df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.set_index('day', inplace=True)

In [ ]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           32          2  Sunny

In [ ]:
df.loc['1/3/2017']

temperature      28
windspeed         2
event          Snow
Name: 1/3/2017, dtype: object

In [ ]:
df.reset_index(inplace = True)

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny