<a href="https://colab.research.google.com/github/icy-agarwal/AIML/blob/main/DAY3_pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("second.csv")

In [ ]:
df

  stocks data     Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4
0     tickers            eps    revenue      price         people
1       GOOGL          27.82         87        845     larry page
2         WMT           4.61        484         65           n.a.
3        MSFT             -1         85         64     bill gates
4         RIL  not available         50       1023  mukesh ambani
5        TATA            5.6         -1       n.a.     ratan tata

In [ ]:
df2 = pd.read_csv("second2.csv")

In [ ]:
df2

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df2 = pd.read_csv("second2.csv", skiprows=1)

In [ ]:
df2

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2   RIL  not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df2= pd.read_csv("second2.csv", header =  None, names=["ticker", "eps", "revenue", "price", "people"])
df2

    ticker            eps  revenue  price         people
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [ ]:
df2

    ticker            eps  revenue  price         people
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [ ]:
df

  stocks data     Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4
0     tickers            eps    revenue      price         people
1       GOOGL          27.82         87        845     larry page
2         WMT           4.61        484         65           n.a.
3        MSFT             -1         85         64     bill gates
4         RIL  not available         50       1023  mukesh ambani
5        TATA            5.6         -1       n.a.     ratan tata

In [ ]:
df = pd.read_csv("second.csv", na_values=["not available", "n.a."])
df

  stocks data Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4
0     tickers        eps    revenue      price         people
1       GOOGL      27.82         87        845     larry page
2         WMT       4.61        484         65            NaN
3        MSFT         -1         85         64     bill gates
4         RIL        NaN         50       1023  mukesh ambani
5        TATA        5.6         -1        NaN     ratan tata

In [ ]:
df2

    ticker            eps  revenue  price         people
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [ ]:
df2 = pd.read_csv("second2.csv", na_values=["not available", "n.a."])
df2

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3     RIL    NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [ ]:
df2 = pd.read_csv("second2.csv", na_values={
    'eps':["not available", "n.a."],
    'revenue':["not available", "n.a.", -1],
    'people':["not available", "n.a."]
})
df2

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3     RIL    NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:
df2.to_csv("new.csv", index=False)

In [ ]:
df2.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [ ]:
df2.to_csv("new.csv", index = False, columns=["tickers", "eps"])