<a href="https://colab.research.google.com/github/icy-agarwal/AIML/blob/main/DAY3_pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("third.csv")

In [ ]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    rain
1   1/4/2017          NaN        9.0   sunny
2   1/5/2017         28.0        NaN    snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    rain
5   1/8/2017          NaN        NaN   sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  cloudy
8  1/11/2017         40.0       12.0   sunny

In [ ]:
type(df.day[0])

str

In [ ]:
df = pd.read_csv("third.csv", parse_dates=["day"])

In [ ]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    rain
1 2017-01-04          NaN        9.0   sunny
2 2017-01-05         28.0        NaN    snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    rain
5 2017-01-08          NaN        NaN   sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  cloudy
8 2017-01-11         40.0       12.0   sunny

In [ ]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
df.set_index('day', inplace = True)

In [ ]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04          NaN        9.0   sunny
2017-01-05         28.0        NaN    snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    rain
2017-01-08          NaN        NaN   sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
#fillna

In [ ]:
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04          0.0        9.0   sunny
2017-01-05         28.0        0.0    snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    rain
2017-01-08          0.0        0.0   sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
new_df = df.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event': 'no event'
})
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      rain
2017-01-04          0.0        9.0     sunny
2017-01-05         28.0        0.0      snow
2017-01-06          0.0        7.0  no event
2017-01-07         32.0        0.0      rain
2017-01-08          0.0        0.0     sunny
2017-01-09          0.0        0.0  no event
2017-01-10         34.0        8.0    cloudy
2017-01-11         40.0       12.0     sunny

In [ ]:
new_df = df.ffill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04         32.0        9.0   sunny
2017-01-05         28.0        9.0    snow
2017-01-06         28.0        7.0    snow
2017-01-07         32.0        7.0    rain
2017-01-08         32.0        7.0   sunny
2017-01-09         32.0        7.0   sunny
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
new_df = df.interpolate(method = "time")
new_df

/tmp/ipykernel_3050/3608406869.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method = "time")

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    rain
2017-01-04    29.000000       9.00   sunny
2017-01-05    28.000000       8.00    snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    rain
2017-01-08    32.666667       7.50   sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  cloudy
2017-01-11    40.000000      12.00   sunny

In [ ]:
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
new_df = df.dropna(how = "all")
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04          NaN        9.0   sunny
2017-01-05         28.0        NaN    snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    rain
2017-01-08          NaN        NaN   sunny
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
new_df = df.dropna(thresh=2)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04          NaN        9.0   sunny
2017-01-05         28.0        NaN    snow
2017-01-07         32.0        NaN    rain
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [ ]:
dt = pd.date_range("01-01-2017", "01-11-2017")
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)
df

            temperature  windspeed   event
2017-01-01         32.0        6.0    rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   sunny
2017-01-05         28.0        NaN    snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    rain
2017-01-08          NaN        NaN   sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny